# Generated by Django 4.1 on 2022-10-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("endereco", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("ano_lancamento", models.DateField()),
                ("valor_locacao", models.FloatField()),
                (
                    "categoria_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.categoria"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Locacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrega", models.DateTimeField()),
                ("data_locacao", models.DateTimeField()),
                ("valor", models.FloatField()),
                (
                    "cliente_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.cliente"
                    ),
                ),
                ("filme_id", models.ManyToManyField(to="main.filme")),
            ],
        ),
    ]
